services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/initdb:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build: .
        container_name: crud
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            ENVIRONMENT: development
            API_PORT: 8080
            PG_HOST: postgres
            PG_PORT: 5432
            PG_USER: postgres
            PG_PASSWORD: postgres
            PG_DATABASE: postgres
            PG_MAX_CONNECTIONS: 100
            PG_MIN_CONNECTIONS: 1
        volumes:
            - .:/app
        command: node ./index.js

volumes:
    postgres_data:
