### Listar empresas
GET http://localhost:8080/companies
Accept: application/json

### Criar empresa
POST http://localhost:8080/companies
Content-Type: application/json

{
 "name": "Hakuna Matata Corp"
}

### Buscar empresa por ID
GET http://localhost:8080/companies/10
Accept: application/json

### Atualizar empresa
PUT http://localhost:8080/companies/2
Content-Type: application/json

{
  "name": "Hakuna Matata Corp Updated"
}

### Deletar empresa
DELETE http://localhost:8080/companies/1
